sorting implemented
Szpytma/nc-games pull request #9
Opened 2023-04-20 14:14 UTC by Szpytma

2023-04-20 14:42 UTC, roisinoreilly requested changes
this is looking really good! Functionality wise everything works great, I've left a few comments about the user experience I'd like you to have a look at, after you've sorted that send me a DM or put in another PR :)

2023-04-20 14:42 UTC, roisinoreilly commented on src/components/Sorting.jsx
> +          checked={isAsc}
it's really not clear to the user that checking this box will flip from ascending to descending

2023-04-20 14:42 UTC, roisinoreilly commented on src/components/Sorting.jsx
> +          <Button>Sort By date</Button>
dropdowns would be much more user friendly than buttons here, especially for the sorting

2023-04-21 09:45 UTC, lewispricey requested changes
Great work on this ticket so far, I really like the catogory dropdown and your buttons to change the sort order.

Currently to change between asc and desc I have to tick/untick the box and then press one of the sort buttons again. Whilst this works it doesnt make for the most straight forward UI.

It would be nice to perhaps have a dropdown for Asc/Desc and when that changes update the sort automaticaly without me having to click a button.

Overall great stuff the apps coming on really well, please could you implement the dropdown or change your toggle so this updates the query without having to do anything extra and raise another PR.

2023-04-21 14:53 UTC, lewispricey approved these changes
Awesome! Thanks for implementing those changes 👍 

Good to merge when you're ready 🚀

2023-04-21 14:58 UTC, merged